### PR TITLE
Remove horizontal bars at top and bottom of recyclerview when scrolling

### PR DESCRIPTION
**Pull request by veyndan**

### CODE REVIEW

**Comment by veyndan** [comment]
Do you mind giving me any information to what was wrong with the PR?

**Comment by CosimoSguanci** [comment]
Excuse me, but i didn't understand so much the pull request

Il 25 nov 2016 9:38 PM, "Veyndan Stuart" <notifications@github.com> ha
scritto:

**Comment by veyndan** [comment]
If you look at the very bottom of the list in the current app (first screen shot), there is a horizontal white bar overlapping the list. In my PR (second screen shot), I have removed that white bar.

screenshot_20161125-205747
screenshot_20161125-205835

**Comment by CosimoSguanci** [comment]
Oh, okay,I'm sorry i'm new to Github. Make another PR and I'll surely
accept it!

Il 25 nov 2016 10:02 PM, "Veyndan Stuart" <notifications@github.com> ha
scritto:

**Comment by veyndan** [comment]
I believe that you can just reopen this one. [http://stackoverflow.com/a/13383299](http://stackoverflow.com/a/13383299)

**Pull request merged**
